### ISSUE TITLE
When using z-index affected elements, it always stays below, even if css is manually changed to a higher z-index  

### ISSUE THREAD

**Issue by urbgimtam** [LuXDAmore/vue-cursor-fx#2]
When working with other components like vue-swiper, or if a specific component has a z-index, the cursor appears below the element. This makes it disappear if, for example, a modal is opened, or if an expandable menu is opened.

**Expected behavior**
Should be always above all other elements on the page. Overwriting the elements' style with 'z-index: 999 !important' doesn't work also.

**Additional context**
Using nuxt 2.13.3, tailwindcss.

PS: Great component, in any case.

**Comment by LuXDAmore** [comment]
Hello @urbgimtam 😅 

Sorry for my late reply, i was travelling for a while and i haven't seen your issue! 😞 

Can you reproduce the problem somewhere so i can check the issue, to try to make a fix?

PS: Thanks for the compliment!!  😄

**Comment by urbgimtam** [comment]
Hi again.

Sorry, I ended up not using vue-cursor-fx when I filed the issue, and forgot about it later on.

In any case, a few days ago I was showing someone vue-cursor-fx and the same issue turned up.

I've found a workaround, you can see it in this codesandbox.
https://x2cbb.sse.codesandbox.io/

**Comment by LuXDAmore** [comment]
Hi @urbgimtam

Thank you very much!
Can You add a PR with your solution?  😄 

So, I can merge it and You can use vue-cursor-fx 😎 

Thanks a lot for your work!!

**Comment by urbgimtam** [comment]
Ok, I'll try to do it. It'll be my first ,🙂

**Comment by LuXDAmore** [comment]
@urbgimtam there is always a first time! 😄 

Thanks for the PR! I'm gonna merge and update the repo and the component today 🌞
