### ISSUE TITLE
data-cursor-hover is not reactive

### ISSUE THREAD

**Issue by Bourbiaux** [LuXDAmore/vue-cursor-fx#3]
Hello LuXDAmore, i use your component for my portfolio and it works great!

But i have a problem : all the "data-cursor-hover" are not reactive for me, i use router-view for my navigation, and only the first page i load in work as expected.
How can i make it reactive? I'm probably missing something. I have the same problem with async components.

thanks in advance for any help on this

**Comment by LuXDAmore** [comment]
Sorry, i didn't get the notification about your issue (i don't know why 🤷🏻‍♂️ )

Can You provide an [example](https://codesandbox.io/)?

If you are using it in VueRouter, and you need to have dynamic **[data-cursor]** attributes, is the component inside each page? Or are You using a layout?

**Comment by LuXDAmore** [comment]
Maybe, it could help You [this](https://stackoverflow.com/a/54940105/3446499)..

I haven't tried it, but i think it could work:
You can add a ref to the `<cursor ref="cursor">` and then You can call the **start()** method.

P.S. : there is a **refresh()** method too, but it doesn't handle events reloading.

P.P.S. : there is a **destroy()** method too, could be used before **start()** to clean the previous settings in the previous route component.

**Comment by Bourbiaux** [comment]
No problem, 
okay,  it kind of work with the start() function. Here is the example  : 
https://codesandbox.io/s/wonderful-varahamihira-098e6?file=/src/main.js
On the skill page, i am calling the start function on the cursor ref. But this is not really working as you can see.

**Comment by LuXDAmore** [comment]
@Bourbiaux I've fixed your example [HERE](https://codesandbox.io/s/dynamic-route-with-vuecursorfx-9hmj3).

You're using Dynamic Imports and Code splitting, so this is why the application can't really know exactly when the DOM is mounted on the child component and can't render again the "data-cursor-hover" attribute.
Using the Vue-`key` prop fix this behavior forcing the `cursor-fx` to re-execute itself at every page change.

Maybe You can also add some transition-effect when `.cursor-fx--loaded` to fix the glitch on re-render.

Hope this helps 🚀 

_P.S.: I've also edited your code to match the guidelines from the Vue-Router plugin, feel free to copy that code if You need it._ 😄

**Comment by Bourbiaux** [comment]
Thanks @LuXDAmore,
it restarts well when the key props have changed! The only thing now is the glitch. The animation trigger from the top left only when the mouse is moving. I don't see how i can fix that with animation or transition. 

Would be nice if we could have a data-refresh function that will only browse the DOM for the new data-cursor-hover. But I don't know if that is possible.

**Comment by LuXDAmore** [comment]
@Bourbiaux yeah, i don't think it could be fixable by a transition (I've made some test), so it's officially a bug 🎉 , i'm gonna fix it in a couple of days 🚀

**Comment by LuXDAmore** [comment]
@Bourbiaux I've added some features, events and classes.

Check out the updated website / documentation and reopen this issue if you think it's not fixed. Thank You 😄
